version: '3'

services:

        keycloak:
                image: jboss/keycloak
                container_name: keycloak
                restart: always
                environment:
                        - KEYCLOAK_USER=admin
                        - KEYCLOAK_PASSWORD=password
                        - KEYCLOAK_LOGLEVEL=INFO
                        - ROOT_LOGLEVEL=INFO                        
                        - PROXY_ADDRESS_FORWARDING=true
                ports:
                        - "8080:8080"
                volumes:
                        - "keycloak-themes:/opt/jboss/keycloak/themes"

volumes:
        keycloak-themes:
                external:
                        name: keycloak-themes
