version: '3'

services:
        
        postgres:
                image: postgres:9.6
                container_name: keycloak-db
                restart: always
                networks:
                        - keycloak-network
                environment:
                        - POSTGRES_USER=keycloak
                        - POSTGRES_DB=keycloak
                        - POSTGRES_PASSWORD=12E45G789p@ssw0rd
                ports:
                        - "5432:5432"
                volumes:
                        - "keycloak-data:/var/lib/postgresql/data:rw"

        keycloak:
                image: jboss/keycloak
                container_name: keycloak
                restart: always
                depends_on: 
                        - postgres
                links:
                        - postgres:postgres
                networks:
                        - keycloak-network
                environment:
                        - KEYCLOAK_USER=admin
                        - KEYCLOAK_PASSWORD=password
                        - KEYCLOAK_LOGLEVEL=INFO
                        - ROOT_LOGLEVEL=INFO                        
                        - PROXY_ADDRESS_FORWARDING=true
                        - DB_VENDOR=postgres
                        - DB_PASSWORD=12E45G789p@ssw0rd
                ports:
                        - "8080:8080"
                volumes:
                        - "keycloak-themes:/opt/jboss/keycloak/themes:ro"

        nginx:
                image: nginx
                container_name: nginx
                restart: always
                links:
                        - keycloak:keycloak
                networks:
                        - keycloak-network
                ports:
                        - "80:80"
                volumes:
                        - "/etc/nginx/nginx.conf:/etc/nginx/nginx.conf:ro"

# Déclaration du network pour la communication entre containeurs
networks:
        keycloak-network:
                driver: bridge

# Déclaration des points de montages (tous externes) des containeurs
volumes:
        keycloak-themes:
                external:
                        name: keycloak-themes
        keycloak-data:
                external:
                        name: keycloak-data
